### ISSUE TITLE
utils. py little tips

### ISSUE THREAD

**Issue by BaseBlank** [Lornatang/RDN-PyTorch#1]
Hello, thank you very much for your excellent work. When I reproduced your code, the code has what I consider to be a minor problem in actual operation. I hope to discuss:
In the utils. py script, the save_ checkpoint () function. For each epoch, a corresponding model parameter. pth file is saved. However, due to the huge number of parameters of the RDN model, the hard disk storage footprint of this .pth file is huge, reaching a size of about 400M. When the training epoch is 1000, hundreds of GB of storage space is needed to save the. pth files for 1000 times. Whether it makes sense to save a  pth file for each epoch. Therefore, whether the following. pth file saving method can be considered; 
```
def save_checkpoint(
        state_dict: dict,
        file_name: str,
        samples_dir: str,
        results_dir: str,
        best_file_name: str,
        last_file_name: str,
        is_best: bool = False,
        is_last: bool = False,
) -> None:
    checkpoint_path = os.path.join(samples_dir, file_name)

    if is_best:
        torch.save(state_dict, checkpoint_path)
        shutil.copyfile(checkpoint_path, os.path.join(results_dir, best_file_name))
    if is_last:
        torch.save(state_dict, checkpoint_path)
        shutil.copyfile(checkpoint_path, os.path.join(results_dir, last_file_name))
```
Thank you again !

**Comment by Lornatang** [comment]
This is work~~

In some scenarios, the recovery pth weights may continue to resume train. You can modify the code according to the actual situation.

Thanks for your interest in my work, it seems like this library was only updated recently.

joke~
